name: "ci"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.7"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4.0.4"
        with:
          node-version: "20.x"
          cache: "npm"

      - run: "npm clean-install"

      - run: "npm run lint"
      - run: "npm run lint:prettier"
      - run: "npm run lint:typescript"
      - run: "npm run build"
      - run: "npm run test"
